sudo: required
services:
  - docker

before_install:
  - docker build -t sekarram84/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sekarram84/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-268809617625"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"